<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
  	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ELearning.Domain\ELearning.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Lessons\DTOs\" />
  </ItemGroup>

</Project>
