@ELearning.API_HostAddress = http://localhost:5277

GET {{ELearning.API_HostAddress}}/openapi/v1.json
Accept: application/json

###

POST {{ELearning.API_HostAddress}}/api/auth/login
Accept: application/json
Content-type: application/json

{
  "Email": "student@elearning.com",
  "Password": "Admin123*"
}

###

POST {{ELearning.API_HostAddress}}/api/auth/login
Accept: application/json
Content-type: application/json

{
  "Email": "instructor@elearning.com",
  "Password": "Admin123*"
}

###

POST {{ELearning.API_HostAddress}}/api/auth/login
Accept: application/json
Content-type: application/json

{
  "Email": "superadmin@elearning.com",
  "Password": "Admin123*"
}

###

POST {{ELearning.API_HostAddress}}/api/auth/login
Accept: application/json
Content-type: application/json

{
  "Email": "admin@elearning.com",
  "Password": "Admin123*"
}